apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayservice
  template:
    metadata:
      labels:
        app: gatewayservice
    spec:
      containers:
      - name: gatewayservice
        image: registry.dev.svc.cluster.local:5000/gatewayservice
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/client_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: "123456"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayservice
spec:
  selector:
    app: gatewayservice
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP