apiVersion: v1
kind: ServiceMonitor
metadata:
  name: clientservice-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: clientservice
  endpoints:
    - port: http          
      path: /actuator/prometheus
      interval: 15s

